### ISSUE TITLE
Work on your Git Activities

### ISSUE THREAD

**Issue by franklinbrian** [FranklinUniversityCompSciPracticum/GitActivities#9]
Make sure to complete activites 1, 2, and 3 by the end of week 2

**Comment by Wmonnh6** [comment]
I am having some issues with the last step of Git Activity 2 that I emailed you about. I cannot figure out the problem I am having with not being able to assign reviewers to my PR.

**Comment by blgorman** [comment]
Thanks for bringing this up.  In order to assign you have to be in the org and if you are on your personal repository or if you are not in the org as a user then you will not be able to assign from the org.
